name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Save chaos-mesh
        run: docker pull ghcr.io/chaos-mesh/chaos-mesh:v2.4.2; docker save ghcr.io/chaos-mesh/chaos-mesh:v2.4.2 -o chaos-mesh.tar.gz
      - name: Save chaos-daemon
        run: docker pull ghcr.io/chaos-mesh/chaos-daemon:v2.4.2; docker save ghcr.io/chaos-mesh/chaos-daemon:v2.4.2 -o chaos-daemon.tar.gz
      - name: Save chaos-dashboard
        run: docker pull ghcr.io/chaos-mesh/chaos-dashboard:v2.4.2; docker save ghcr.io/chaos-mesh/chaos-dashboard:v2.4.2 -o chaos-dashboard.tar.gz
      - uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          delete_release: true
          tag_name: latest_docker_image
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Tag release
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest_docker_image

      # Creates the new release with the binary as a release asset.
      # If the previous Action was skipped, then this keeps the same tag as the
      # previous release.
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          body: "Latest docker image"
          name: "latest docker image"
          tag_name: latest_docker_image
          files: |
            chaos-mesh.tar.gz
            chaos-daemon.tar.gz
            chaos-dashboard.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
